CREATE TABLE tb_frame_record (
CONCAT_FRAME VARCHAR(200) NULL ,-- concatFrame
CONCAT_DATA VARCHAR(200) NULL ,-- concatData
PROCESSOR VARCHAR(200) NULL ,-- processor
PROCESSOR_ID VARCHAR(200) NULL ,-- processorId
CONTEXT VARCHAR(200) NULL ,-- context
CHOSEN VARCHAR(200) NULL ,-- chosen

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT '1' ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG text NULL, 
ORG_TREE text NULL, 
) ENGINE=MyISAM;
ALTER TABLE `tb_frame_record` ADD FULLTEXT `fidx_tb_frame_record_orgTree` (`ORG_TREE`);