CREATE TABLE tb_frame_record (
CONCAT_FRAME NVARCHAR(200) NULL ,--concatFrame
CONCAT_DATA NVARCHAR(200) NULL ,--concatData
PROCESSOR NVARCHAR(200) NULL ,--processor
PROCESSOR_ID NVARCHAR(200) NULL ,--processorId
CONTEXT NVARCHAR(200) NULL ,--context
CHOSEN NVARCHAR(200) NULL ,--chosen

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG NVARCHAR(4000) NULL, 
 ORG_TREE NVARCHAR(4000) NULL 
)