CREATE TABLE TB_FRAME_RECORD (
CONCAT_FRAME VARCHAR2(255) NULL ,--concatFrame
CONCAT_DATA VARCHAR2(255) NULL ,--concatData
PROCESSOR VARCHAR2(255) NULL ,--processor
PROCESSOR_ID VARCHAR2(255) NULL ,--processorId
CONTEXT VARCHAR2(255) NULL ,--context
CHOSEN VARCHAR2(255) NULL ,--chosen

ID VARCHAR2(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1)  DEFAULT ('1') ,
CREATED VARCHAR2(32) NULL ,
CREATE_TIME DATE NULL ,
UPDATED VARCHAR2(32) NULL ,
UPDATE_TIME DATE NULL, 
ORG VARCHAR2(4000) NULL, 
 ORG_TREE VARCHAR2(4000) NULL 
)