CREATE TABLE TB_HOLIDAY (
PRAY_ER VARCHAR2(255) NULL ,--申请人
PRAY_ER_ID VARCHAR2(255) NULL ,--申请人ID
PRAY_DAYS VARCHAR2(255) NULL ,--请假时间
REASON VARCHAR2(255) NULL ,--请假理由
FROM_DAYS VARCHAR2(255) NULL ,--开始时间
TO_DAYS VARCHAR2(255) NULL ,--结束时间
TYPE VARCHAR2(255) NULL ,--请假类型
DONER VARCHAR2(255) NULL ,--doner
WITHIN VARCHAR2(255) NULL ,--within

ID VARCHAR2(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1)  DEFAULT ('1') ,
CREATED VARCHAR2(32) NULL ,
CREATE_TIME DATE NULL ,
UPDATED VARCHAR2(32) NULL ,
UPDATE_TIME DATE NULL, 
ORG VARCHAR2(4000) NULL, 
 ORG_TREE VARCHAR2(4000) NULL 
)