CREATE TABLE tb_holiday (
PRAY_ER NVARCHAR(200) NULL ,--申请人
PRAY_ER_ID NVARCHAR(200) NULL ,--申请人ID
PRAY_DAYS NVARCHAR(200) NULL ,--请假时间
REASON NVARCHAR(200) NULL ,--请假理由
FROM_DAYS NVARCHAR(200) NULL ,--开始时间
TO_DAYS NVARCHAR(200) NULL ,--结束时间
TYPE NVARCHAR(200) NULL ,--请假类型
DONER NVARCHAR(200) NULL ,--doner
WITHIN NVARCHAR(200) NULL ,--within

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG NVARCHAR(4000) NULL, 
 ORG_TREE NVARCHAR(4000) NULL 
)