CREATE TABLE tb_holiday (
PRAY_ER VARCHAR(200) NULL ,-- 申请人
PRAY_ER_ID VARCHAR(200) NULL ,-- 申请人ID
PRAY_DAYS VARCHAR(200) NULL ,-- 请假时间
REASON VARCHAR(200) NULL ,-- 请假理由
FROM_DAYS VARCHAR(200) NULL ,-- 开始时间
TO_DAYS VARCHAR(200) NULL ,-- 结束时间
TYPE VARCHAR(200) NULL ,-- 请假类型
DONER VARCHAR(200) NULL ,-- doner
WITHIN VARCHAR(200) NULL ,-- within

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT '1' ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG text NULL, 
ORG_TREE text NULL, 
) ENGINE=MyISAM;
ALTER TABLE `tb_holiday` ADD FULLTEXT `fidx_tb_holiday_orgTree` (`ORG_TREE`);