CREATE TABLE TB_BY_WATCHERS_INFO (
BY_WATCHERS_NAME VARCHAR2(255) NULL ,--被监控者名称
BY_WATCHERS_ID VARCHAR2(255) NULL ,--被监控者编号
WATCH_ID VARCHAR2(255) NULL ,--监控信息编号

ID VARCHAR2(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1)  DEFAULT ('1') ,
CREATED VARCHAR2(32) NULL ,
CREATE_TIME DATE NULL ,
UPDATED VARCHAR2(32) NULL ,
UPDATE_TIME DATE NULL, 
ORG VARCHAR2(4000) NULL, 
 ORG_TREE VARCHAR2(4000) NULL 
)