CREATE TABLE tb_by_watchers_info (
BY_WATCHERS_NAME NVARCHAR(200) NULL ,--被监控者名称
BY_WATCHERS_ID NVARCHAR(200) NULL ,--被监控者编号
WATCH_ID NVARCHAR(200) NULL ,--监控信息编号

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG NVARCHAR(4000) NULL, 
 ORG_TREE NVARCHAR(4000) NULL 
)