CREATE TABLE tb_by_watchers_info (
BY_WATCHERS_NAME VARCHAR(200) NULL ,--被监控者名称
BY_WATCHERS_ID VARCHAR(200) NULL ,--被监控者编号
WATCH_ID VARCHAR(200) NULL ,--监控信息编号

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT '1' ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATE_TIME DATETIME NULL, 
ORG text NULL, 
ORG_TREE text NULL, 
PRIMARY KEY(ID) 
)