CREATE TABLE tb_login_record (
USER_ID NVARCHAR(200) NULL ,--用户Id
USER_NAME NVARCHAR(200) NULL ,--用户名
LOGIN_TIME NVARCHAR(200) NULL ,--登陆时间
LOGIN_TAG NVARCHAR(200) NULL ,--登陆标记
DEPT_ID NVARCHAR(200) NULL ,--部门Id

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG NVARCHAR(4000) NULL, 
 ORG_TREE NVARCHAR(4000) NULL 
)