CREATE TABLE tb_sys_dept_authority (
BM_ID NVARCHAR(200) NULL ,--bmId
JGHY NVARCHAR(200) NULL ,--jghy
DQM NVARCHAR(200) NULL ,--dqm
QXDM NVARCHAR(200) NULL ,--qxdm

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG NVARCHAR(4000) NULL, 
 ORG_TREE NVARCHAR(4000) NULL 
)