CREATE TABLE TB_SYS_DEPT_AUTHORITY (
BM_ID VARCHAR2(255) NULL ,--bmId
JGHY VARCHAR2(255) NULL ,--jghy
DQM VARCHAR2(255) NULL ,--dqm
QXDM VARCHAR2(255) NULL ,--qxdm

ID VARCHAR2(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1)  DEFAULT ('1') ,
CREATED VARCHAR2(32) NULL ,
CREATE_TIME DATE NULL ,
UPDATED VARCHAR2(32) NULL ,
UPDATE_TIME DATE NULL, 
ORG VARCHAR2(4000) NULL, 
 ORG_TREE VARCHAR2(4000) NULL 
)