CREATE TABLE TB_SYS_GRID_SYSTEM (
ZYFZR VARCHAR2(255) NULL ,--主要负责人
ZYFZR_AQZZ VARCHAR2(255) NULL ,--主要负责人安全职责
FGFZR VARCHAR2(255) NULL ,--分管负责人
FGFZR_AQZZ VARCHAR2(255) NULL ,--分管负责人安全职责
DZGDLD VARCHAR2(255) NULL ,--党政挂点领导
DZGDLD_AQZZ VARCHAR2(255) NULL ,--党政挂点领导安全职责
BMGDLD VARCHAR2(255) NULL ,--部门挂点领导
BMGDLD_AQZZ VARCHAR2(255) NULL ,--部门挂点领导安全职责
SDJGZR VARCHAR2(255) NULL ,--属地监管责任
MBZRS VARCHAR2(255) NULL ,--目标责任书

ID VARCHAR2(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1)  DEFAULT ('1') ,
CREATED VARCHAR2(32) NULL ,
CREATE_TIME DATE NULL ,
UPDATED VARCHAR2(32) NULL ,
UPDATE_TIME DATE NULL, 
ORG VARCHAR2(4000) NULL, 
 ORG_TREE VARCHAR2(4000) NULL 
)