CREATE TABLE tb_sys_grid_system (
ZYFZR NVARCHAR(200) NULL ,--主要负责人
ZYFZR_AQZZ NVARCHAR(200) NULL ,--主要负责人安全职责
FGFZR NVARCHAR(200) NULL ,--分管负责人
FGFZR_AQZZ NVARCHAR(200) NULL ,--分管负责人安全职责
DZGDLD NVARCHAR(200) NULL ,--党政挂点领导
DZGDLD_AQZZ NVARCHAR(200) NULL ,--党政挂点领导安全职责
BMGDLD NVARCHAR(200) NULL ,--部门挂点领导
BMGDLD_AQZZ NVARCHAR(200) NULL ,--部门挂点领导安全职责
SDJGZR NVARCHAR(200) NULL ,--属地监管责任
MBZRS NVARCHAR(200) NULL ,--目标责任书

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG NVARCHAR(4000) NULL, 
 ORG_TREE NVARCHAR(4000) NULL 
)