CREATE TABLE tb_system_configure (
DATA_CODE NVARCHAR(200) NULL ,--参数码
DATA_NAME NVARCHAR(200) NULL ,--参数名称
DATA_VALUE NVARCHAR(200) NULL ,--参数值
DATA_DESCRIBE NVARCHAR(200) NULL ,--参数描述
DATA_TYPE NVARCHAR(200) NULL ,--参数类型

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG NVARCHAR(4000) NULL, 
 ORG_TREE NVARCHAR(4000) NULL 
)