CREATE TABLE TB_SYSTEM_CONFIGURE (
DATA_CODE VARCHAR2(255) NULL ,--参数码
DATA_NAME VARCHAR2(255) NULL ,--参数名称
DATA_VALUE VARCHAR2(255) NULL ,--参数值
DATA_DESCRIBE VARCHAR2(255) NULL ,--参数描述
DATA_TYPE VARCHAR2(255) NULL ,--参数类型

ID VARCHAR2(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1)  DEFAULT ('1') ,
CREATED VARCHAR2(32) NULL ,
CREATE_TIME DATE NULL ,
UPDATED VARCHAR2(32) NULL ,
UPDATE_TIME DATE NULL, 
ORG VARCHAR2(4000) NULL, 
 ORG_TREE VARCHAR2(4000) NULL 
)