DROP TABLE IF EXISTS tb_system_configure;
CREATE TABLE tb_system_configure (
DATA_CODE VARCHAR(100) NULL ,-- 参数码
DATA_NAME VARCHAR(100) NULL ,-- 参数名称
DATA_VALUE VARCHAR(200) NULL ,-- 参数值
DATA_DESCRIBE VARCHAR(500) NULL ,-- 参数描述
DATA_TYPE VARCHAR(10) NULL ,-- 参数类型

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT '1' ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG text NULL, 
ORG_TREE text NULL
);