CREATE TABLE sys_tableCreater (
MODULE_NAME NVARCHAR(255) NULL ,--模块名
TABLE_NAME NVARCHAR(255) NULL ,--表名

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL
)