CREATE TABLE SYS_WATCH (
WATCHERS NVARCHAR(MAX) NULL ,--监控者
WATCHERS_SHOW NVARCHAR(MAX) NULL ,--监控者
MODULES NVARCHAR(MAX) NULL ,--模块
MODULES_SHOW NVARCHAR(MAX) NULL ,--模块
BY_WATCHERS NVARCHAR(MAX) NULL ,--被监控者
BY_WATCHERS_SHOW NVARCHAR(MAX) NULL ,--被监控者

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL 
)