CREATE TABLE tb_reversion (
RE_TYPE VARCHAR(200) NULL ,-- 内容
CONTEXT VARCHAR(200) NULL ,-- 详细
REVER VARCHAR(200) NULL ,-- 批复人
CONVERT_ID VARCHAR(200) NULL ,-- 关联ID

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT '1' ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG text NULL, 
ORG_TREE text NULL, 
) ENGINE=MyISAM;
ALTER TABLE `tb_reversion` ADD FULLTEXT `fidx_tb_reversion_orgTree` (`ORG_TREE`);