CREATE TABLE TB_REVERSION (
RE_TYPE VARCHAR2(255) NULL ,--内容
CONTEXT VARCHAR2(255) NULL ,--详细
REVER VARCHAR2(255) NULL ,--批复人
CONVERT_ID VARCHAR2(255) NULL ,--关联ID

ID VARCHAR2(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1)  DEFAULT ('1') ,
CREATED VARCHAR2(32) NULL ,
CREATE_TIME DATE NULL ,
UPDATED VARCHAR2(32) NULL ,
UPDATE_TIME DATE NULL, 
ORG VARCHAR2(4000) NULL, 
 ORG_TREE VARCHAR2(4000) NULL 
)