CREATE TABLE tb_reversion (
RE_TYPE NVARCHAR(200) NULL ,--内容
CONTEXT NVARCHAR(200) NULL ,--详细
REVER NVARCHAR(200) NULL ,--批复人
CONVERT_ID NVARCHAR(200) NULL ,--关联ID

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG NVARCHAR(4000) NULL, 
 ORG_TREE NVARCHAR(4000) NULL 
)