CREATE TABLE tb_borrow (
BORROWER NVARCHAR(200) NULL ,--借款人
BORROWER_ID NVARCHAR(200) NULL ,--借款人ID
REASON NVARCHAR(200) NULL ,--借款事由
AMOUNT NVARCHAR(200) NULL ,--借款金额
PRAY_TIME NVARCHAR(200) NULL ,--申请时间
DONER NVARCHAR(200) NULL ,--doner
WITHIN NVARCHAR(200) NULL ,--within
STEP NVARCHAR(200) NULL ,--step

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG NVARCHAR(4000) NULL, 
 ORG_TREE NVARCHAR(4000) NULL 
)