CREATE TABLE tb_borrow (
BORROWER VARCHAR(200) NULL ,-- 借款人
BORROWER_ID VARCHAR(200) NULL ,-- 借款人ID
REASON VARCHAR(200) NULL ,-- 借款事由
AMOUNT VARCHAR(200) NULL ,-- 借款金额
PRAY_TIME VARCHAR(200) NULL ,-- 申请时间
DONER VARCHAR(200) NULL ,-- doner
WITHIN VARCHAR(200) NULL ,-- within
STEP VARCHAR(200) NULL ,-- step

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT '1' ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG text NULL, 
ORG_TREE text NULL, 
) ENGINE=MyISAM;
ALTER TABLE `tb_borrow` ADD FULLTEXT `fidx_tb_borrow_orgTree` (`ORG_TREE`);