CREATE TABLE TB_SYS_ICON (
ICON_NO int identity(1,1), --图标编号
NAME NVARCHAR(255) NULL ,--图标名称
ICON varbinary(MAX) NULL ,--图标
ICON_DESC NVARCHAR(255) NULL ,--图标描述
TYPE NVARCHAR(255) NULL ,--图标类型

STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
constraint pkid primary key (ICON_NO)
)