CREATE TABLE TB_REIMBURSE_LIST (
PROJECT_NAME VARCHAR2(255) NULL ,--付款事由
BZ VARCHAR2(255) NULL ,--备注摘要
AMOUNT VARCHAR2(255) NULL ,--金额
RELATE_DATA VARCHAR2(255) NULL ,--relateData

ID VARCHAR2(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1)  DEFAULT ('1') ,
CREATED VARCHAR2(32) NULL ,
CREATE_TIME DATE NULL ,
UPDATED VARCHAR2(32) NULL ,
UPDATE_TIME DATE NULL, 
ORG VARCHAR2(4000) NULL, 
 ORG_TREE VARCHAR2(4000) NULL 
)