CREATE TABLE tb_reimburse_list (
PROJECT_NAME VARCHAR(200) NULL ,-- 付款事由
BZ VARCHAR(200) NULL ,-- 备注摘要
AMOUNT VARCHAR(200) NULL ,-- 金额
RELATE_DATA VARCHAR(200) NULL ,-- relateData

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT '1' ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG text NULL, 
ORG_TREE text NULL, 
) ENGINE=MyISAM;
ALTER TABLE `tb_reimburse_list` ADD FULLTEXT `fidx_tb_reimburse_list_orgTree` (`ORG_TREE`);