CREATE TABLE tb_reimburse (
REIMBURSE_TITLE VARCHAR(200) NULL ,-- 报销事由
REIMURSE_TIME VARCHAR(200) NULL ,-- 报销时间
REIMURSER VARCHAR(200) NULL ,-- 报销人
REIMURSER_ID VARCHAR(200) NULL ,-- 报销人ID
REMIURSER_JOB VARCHAR(200) NULL ,-- 报销人部门
REMIURSE_HOLE VARCHAR(200) NULL ,-- 报销总金额
DOCS VARCHAR(200) NULL ,-- 共副单据
DONER VARCHAR(200) NULL ,-- doner
WITHIN VARCHAR(200) NULL ,-- within
STEP VARCHAR(200) NULL ,-- step

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT '1' ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG text NULL, 
ORG_TREE text NULL, 
) ENGINE=MyISAM;
ALTER TABLE `tb_reimburse` ADD FULLTEXT `fidx_tb_reimburse_orgTree` (`ORG_TREE`);