CREATE TABLE tb_reimburse (
REIMBURSE_TITLE NVARCHAR(200) NULL ,--报销事由
REIMURSE_TIME NVARCHAR(200) NULL ,--报销时间
REIMURSER NVARCHAR(200) NULL ,--报销人
REIMURSER_ID NVARCHAR(200) NULL ,--报销人ID
REMIURSER_JOB NVARCHAR(200) NULL ,--报销人部门
REMIURSE_HOLE NVARCHAR(200) NULL ,--报销总金额
DOCS NVARCHAR(200) NULL ,--共副单据
DONER NVARCHAR(200) NULL ,--doner
WITHIN NVARCHAR(200) NULL ,--within
STEP NVARCHAR(200) NULL ,--step

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG NVARCHAR(4000) NULL, 
 ORG_TREE NVARCHAR(4000) NULL 
)