CREATE TABLE TB_REIMBURSE (
REIMBURSE_TITLE VARCHAR2(255) NULL ,--报销事由
REIMURSE_TIME VARCHAR2(255) NULL ,--报销时间
REIMURSER VARCHAR2(255) NULL ,--报销人
REIMURSER_ID VARCHAR2(255) NULL ,--报销人ID
REMIURSER_JOB VARCHAR2(255) NULL ,--报销人部门
REMIURSE_HOLE VARCHAR2(255) NULL ,--报销总金额
DOCS VARCHAR2(255) NULL ,--共副单据
DONER VARCHAR2(255) NULL ,--doner
WITHIN VARCHAR2(255) NULL ,--within
STEP VARCHAR2(255) NULL ,--step

ID VARCHAR2(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1)  DEFAULT ('1') ,
CREATED VARCHAR2(32) NULL ,
CREATE_TIME DATE NULL ,
UPDATED VARCHAR2(32) NULL ,
UPDATE_TIME DATE NULL, 
ORG VARCHAR2(4000) NULL, 
 ORG_TREE VARCHAR2(4000) NULL 
)