CREATE TABLE tb_worker (
NAME VARCHAR(200) NULL ,-- 员工姓名
HEADER VARCHAR(200) NULL ,-- 头像
EMAIL VARCHAR(200) NULL ,-- 邮箱地址
MOBILE VARCHAR(200) NULL ,-- 手机
DEPT VARCHAR(200) NULL ,-- 所在部门
POSITION VARCHAR(200) NULL ,-- 职位
OWNER_INTUR VARCHAR(200) NULL ,-- 状态

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT '1' ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG text NULL, 
ORG_TREE text NULL, 
) ENGINE=MyISAM;
ALTER TABLE `tb_worker` ADD FULLTEXT `fidx_tb_worker_orgTree` (`ORG_TREE`);