CREATE TABLE tb_worker (
NAME NVARCHAR(200) NULL ,--员工姓名
HEADER NVARCHAR(200) NULL ,--头像
EMAIL NVARCHAR(200) NULL ,--邮箱地址
MOBILE NVARCHAR(200) NULL ,--手机
DEPT NVARCHAR(200) NULL ,--所在部门
POSITION NVARCHAR(200) NULL ,--职位
OWNER_INTUR NVARCHAR(200) NULL ,--状态

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG NVARCHAR(4000) NULL, 
 ORG_TREE NVARCHAR(4000) NULL 
)