CREATE TABLE TB_SQUSER (
CITY_CODE VARCHAR2(255) NULL ,--城市代码
CITY_NAME VARCHAR2(255) NULL ,--市
AREA_CODE VARCHAR2(255) NULL ,--区代码
AREA_NAME VARCHAR2(255) NULL ,--区名称
STREET_CODE VARCHAR2(255) NULL ,--街道代码
STREET_NAME VARCHAR2(255) NULL ,--街道名称
COMMUNITY_CODE VARCHAR2(255) NULL ,--社区代码
COMMUNITY_NAME VARCHAR2(255) NULL ,--社区名称
SQFZR VARCHAR2(255) NULL ,--社区负责人
TELPHONE VARCHAR2(255) NULL ,--联系电话
EMAIL VARCHAR2(255) NULL ,--邮箱
TEL_NO VARCHAR2(255) NULL ,--固定电话
PARAMA VARCHAR2(255) NULL ,--预留字段a
PARAMB VARCHAR2(255) NULL ,--预留字段b
PARAMC VARCHAR2(255) NULL ,--预留字段c
PARAMD VARCHAR2(255) NULL ,--预留字段d
PARAME VARCHAR2(255) NULL ,--预留字段e

ID VARCHAR2(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1)  DEFAULT ('1') ,
CREATED VARCHAR2(32) NULL ,
CREATE_TIME DATE NULL ,
UPDATED VARCHAR2(32) NULL ,
UPDATE_TIME DATE NULL, 
ORG VARCHAR2(4000) NULL, 
 ORG_TREE VARCHAR2(4000) NULL 
)