CREATE TABLE tb_squser (
CITY_CODE VARCHAR(200) NULL ,-- 城市代码
CITY_NAME VARCHAR(200) NULL ,-- 市
AREA_CODE VARCHAR(200) NULL ,-- 区代码
AREA_NAME VARCHAR(200) NULL ,-- 区名称
STREET_CODE VARCHAR(200) NULL ,-- 街道代码
STREET_NAME VARCHAR(200) NULL ,-- 街道名称
COMMUNITY_CODE VARCHAR(200) NULL ,-- 社区代码
COMMUNITY_NAME VARCHAR(200) NULL ,-- 社区名称
SQFZR VARCHAR(200) NULL ,-- 社区负责人
TELPHONE VARCHAR(200) NULL ,-- 联系电话
EMAIL VARCHAR(200) NULL ,-- 邮箱
TEL_NO VARCHAR(200) NULL ,-- 固定电话
PARAMA VARCHAR(200) NULL ,-- 预留字段a
PARAMB VARCHAR(200) NULL ,-- 预留字段b
PARAMC VARCHAR(200) NULL ,-- 预留字段c
PARAMD VARCHAR(200) NULL ,-- 预留字段d
PARAME VARCHAR(200) NULL ,-- 预留字段e

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT '1' ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG text NULL, 
ORG_TREE text NULL, 
);
ALTER TABLE `tb_squser` ADD FULLTEXT `fidx_tb_squser_orgTree` (`ORG_TREE`)