CREATE TABLE tb_squser (
CITY_CODE NVARCHAR(200) NULL ,--城市代码
CITY_NAME NVARCHAR(200) NULL ,--市
AREA_CODE NVARCHAR(200) NULL ,--区代码
AREA_NAME NVARCHAR(200) NULL ,--区名称
STREET_CODE NVARCHAR(200) NULL ,--街道代码
STREET_NAME NVARCHAR(200) NULL ,--街道名称
COMMUNITY_CODE NVARCHAR(200) NULL ,--社区代码
COMMUNITY_NAME NVARCHAR(200) NULL ,--社区名称
SQFZR NVARCHAR(200) NULL ,--社区负责人
TELPHONE NVARCHAR(200) NULL ,--联系电话
EMAIL NVARCHAR(200) NULL ,--邮箱
TEL_NO NVARCHAR(200) NULL ,--固定电话
PARAMA NVARCHAR(200) NULL ,--预留字段a
PARAMB NVARCHAR(200) NULL ,--预留字段b
PARAMC NVARCHAR(200) NULL ,--预留字段c
PARAMD NVARCHAR(200) NULL ,--预留字段d
PARAME NVARCHAR(200) NULL ,--预留字段e

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG NVARCHAR(4000) NULL, 
 ORG_TREE NVARCHAR(4000) NULL 
)