CREATE TABLE tb_reporting (
TITLE NVARCHAR(200) NULL ,--回报标题
REPORTER NVARCHAR(200) NULL ,--汇报人
REPORT_TIME NVARCHAR(200) NULL ,--汇报时间
REPORT_TYPE NVARCHAR(200) NULL ,--汇报类型
CONTEXT NVARCHAR(200) NULL ,--汇报内容
CHECKER NVARCHAR(200) NULL ,--审阅人
OWNER NVARCHAR(200) NULL ,--拥有者
STEPS NVARCHAR(200) NULL ,--当前步骤
INFORMRE NVARCHAR(200) NULL ,--经办人

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG NVARCHAR(4000) NULL, 
 ORG_TREE NVARCHAR(4000) NULL 
)