CREATE TABLE TB_REPORTING (
TITLE VARCHAR2(255) NULL ,--回报标题
REPORTER VARCHAR2(255) NULL ,--汇报人
REPORT_TIME VARCHAR2(255) NULL ,--汇报时间
REPORT_TYPE VARCHAR2(255) NULL ,--汇报类型
CONTEXT VARCHAR2(255) NULL ,--汇报内容
CHECKER VARCHAR2(255) NULL ,--审阅人
OWNER VARCHAR2(255) NULL ,--拥有者
STEPS VARCHAR2(255) NULL ,--当前步骤
INFORMRE VARCHAR2(255) NULL ,--经办人

ID VARCHAR2(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1)  DEFAULT ('1') ,
CREATED VARCHAR2(32) NULL ,
CREATE_TIME DATE NULL ,
UPDATED VARCHAR2(32) NULL ,
UPDATE_TIME DATE NULL, 
ORG VARCHAR2(4000) NULL, 
 ORG_TREE VARCHAR2(4000) NULL 
)