CREATE TABLE tb_reporting (
TITLE VARCHAR(200) NULL ,-- 回报标题
REPORTER VARCHAR(200) NULL ,-- 汇报人
REPORT_TIME VARCHAR(200) NULL ,-- 汇报时间
REPORT_TYPE VARCHAR(200) NULL ,-- 汇报类型
CONTEXT VARCHAR(200) NULL ,-- 汇报内容
CHECKER VARCHAR(200) NULL ,-- 审阅人
OWNER VARCHAR(200) NULL ,-- 拥有者
STEPS VARCHAR(200) NULL ,-- 当前步骤
INFORMRE VARCHAR(200) NULL ,-- 经办人

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT '1' ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG text NULL, 
ORG_TREE text NULL, 
) ENGINE=MyISAM;
ALTER TABLE `tb_reporting` ADD FULLTEXT `fidx_tb_reporting_orgTree` (`ORG_TREE`);