CREATE TABLE tb_statistics (
SHOWN VARCHAR(200) NULL ,-- shown
VALUE VARCHAR(200) NULL ,-- value
NUM VARCHAR(200) NULL ,-- num

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT '1' ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG text NULL, 
ORG_TREE text NULL, 
) ENGINE=MyISAM;
ALTER TABLE `tb_statistics` ADD FULLTEXT `fidx_tb_statistics_orgTree` (`ORG_TREE`);