CREATE TABLE tb_statistics (
SHOWN NVARCHAR(200) NULL ,--shown
VALUE NVARCHAR(200) NULL ,--value
NUM NVARCHAR(200) NULL ,--num

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG NVARCHAR(4000) NULL, 
 ORG_TREE NVARCHAR(4000) NULL 
)