CREATE TABLE TB_STATISTICS (
SHOWN VARCHAR2(255) NULL ,--shown
VALUE VARCHAR2(255) NULL ,--value
NUM VARCHAR2(255) NULL ,--num

ID VARCHAR2(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1)  DEFAULT ('1') ,
CREATED VARCHAR2(32) NULL ,
CREATE_TIME DATE NULL ,
UPDATED VARCHAR2(32) NULL ,
UPDATE_TIME DATE NULL, 
ORG VARCHAR2(4000) NULL, 
 ORG_TREE VARCHAR2(4000) NULL 
)