CREATE TABLE TB_TEST (
NAME NVARCHAR(255) NULL ,--名称
STYLE NVARCHAR(255) NULL ,--风格

ORG NVARCHAR(MAX) NULL ,--部门id
ORG_TREE NVARCHAR(MAX) NULL ,--部门用户结构

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL 
)