CREATE TABLE tb_work_station (
MODLE VARCHAR(200) NULL ,-- 模块
NUMBER VARCHAR(200) NULL ,-- 数据数
SHOW_DATA VARCHAR(200) NULL ,-- 数据列表

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT '1' ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG text NULL, 
ORG_TREE text NULL, 
) ENGINE=MyISAM;
ALTER TABLE `tb_work_station` ADD FULLTEXT `fidx_tb_work_station_orgTree` (`ORG_TREE`);