CREATE TABLE tb_work_station (
MODLE NVARCHAR(200) NULL ,--模块
NUMBER NVARCHAR(200) NULL ,--数据数
SHOW_DATA NVARCHAR(200) NULL ,--数据列表

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG NVARCHAR(4000) NULL, 
 ORG_TREE NVARCHAR(4000) NULL 
)