CREATE TABLE TB_WORK_STATION (
MODLE VARCHAR2(255) NULL ,--模块
NUMBER VARCHAR2(255) NULL ,--数据数
SHOW_DATA VARCHAR2(255) NULL ,--数据列表

ID VARCHAR2(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1)  DEFAULT ('1') ,
CREATED VARCHAR2(32) NULL ,
CREATE_TIME DATE NULL ,
UPDATED VARCHAR2(32) NULL ,
UPDATE_TIME DATE NULL, 
ORG VARCHAR2(4000) NULL, 
 ORG_TREE VARCHAR2(4000) NULL 
)