CREATE TABLE sys_columns (
SHEET_ID NVARCHAR(255) NULL ,--所属表
COLUMN_E_N NVARCHAR(255) NULL ,--英文名称
COLUMN_C_H NVARCHAR(255) NULL ,--中文名称
TYPE NVARCHAR(255) NULL ,--字段类型
LENGTH NVARCHAR(255) NULL ,--字段长度
ENABLE_DATA NVARCHAR(255) NULL ,--是否关联元数据
DEV_DATA NVARCHAR(255) NULL ,--元数据
ADDUCTION NVARCHAR(255) NULL ,--数据引用
ENABLE NVARCHAR(255) NULL ,--是否启用
ORDER NVARCHAR(255) NULL ,--显示顺序
IS_NULL NVARCHAR(255) NULL ,--是否为空
VALIDATE NVARCHAR(255) NULL ,--验证
PROMPT NVARCHAR(255) NULL ,--错误提示

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL
)