CREATE TABLE TB_MOBULE (
TYPE NVARCHAR(255) NULL ,--模块分类
MOBULE_ID NVARCHAR(255) NULL ,--模块Code
MOBULE_NAME NVARCHAR(255) NULL ,--模块名
MOBULE_DESC NVARCHAR(255) NULL ,--模块描述

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG NVARCHAR(MAX) NULL, 
 ORG_TREE NVARCHAR(MAX) NULL 
)