CREATE TABLE TB_TEST_CODE_CREATER (
SHOW_VIEW NVARCHAR(255) NULL ,--测试代码字段1
SHOW_VIDEO NVARCHAR(255) NULL ,--测试代码字段2

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL 
)