CREATE TABLE tb_frame_control (
RELATION_ID VARCHAR(200) NULL ,-- 对应ID
LAST_ID VARCHAR(200) NULL ,-- 上一步ID
NEXT_ID VARCHAR(200) NULL ,-- 下一步ID
IS_LAST VARCHAR(200) NULL ,-- 是否最后一步
DESINER_ID VARCHAR(200) NULL ,-- 处理人

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT '1' ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG text NULL, 
ORG_TREE text NULL 
) 
ALTER TABLE `tb_frame_control` ADD FULLTEXT `fidx_tb_frame_control_orgTree` (`ORG_TREE`);