CREATE TABLE TB_ONLIN_CHECKIN (
CHECKIN_USER VARCHAR2(255) NULL ,--checkinUser
CHECKEIN_TIME VARCHAR2(255) NULL ,--checkeinTime
CHECKIN_ADDRESS VARCHAR2(255) NULL ,--checkinAddress
PIC_URL VARCHAR2(255) NULL ,--picUrl
CHECKIN_TYPE VARCHAR2(255) NULL ,--checkinType
FILE_NAME VARCHAR2(255) NULL ,--fileName
CONTENT_TYPE VARCHAR2(255) NULL ,--contentType

ID VARCHAR2(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1)  DEFAULT ('1') ,
CREATED VARCHAR2(32) NULL ,
CREATE_TIME DATE NULL ,
UPDATED VARCHAR2(32) NULL ,
UPDATE_TIME DATE NULL, 
ORG VARCHAR2(4000) NULL, 
 ORG_TREE VARCHAR2(4000) NULL 
)