CREATE TABLE tb_onlin_checkin (
CHECKIN_USER NVARCHAR(200) NULL ,--checkinUser
CHECKEIN_TIME NVARCHAR(200) NULL ,--checkeinTime
CHECKIN_ADDRESS NVARCHAR(200) NULL ,--checkinAddress
PIC_URL NVARCHAR(200) NULL ,--picUrl
CHECKIN_TYPE NVARCHAR(200) NULL ,--checkinType
FILE_NAME NVARCHAR(200) NULL ,--fileName
CONTENT_TYPE NVARCHAR(200) NULL ,--contentType

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG NVARCHAR(4000) NULL, 
 ORG_TREE NVARCHAR(4000) NULL 
)