CREATE TABLE tb_job_remind (
MODEL VARCHAR(200) NULL ,-- model
NAME VARCHAR(200) NULL ,-- name
TIME VARCHAR(200) NULL ,-- time
OWNER VARCHAR(200) NULL ,-- owner
CREATOR VARCHAR(200) NULL ,-- creator

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT '1' ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG text NULL, 
ORG_TREE text NULL, 
) ENGINE=MyISAM;
ALTER TABLE `tb_job_remind` ADD FULLTEXT `fidx_tb_job_remind_orgTree` (`ORG_TREE`);