CREATE TABLE TB_JOB_REMIND (
MODEL VARCHAR2(255) NULL ,--model
NAME VARCHAR2(255) NULL ,--name
TIME VARCHAR2(255) NULL ,--time
OWNER VARCHAR2(255) NULL ,--owner
CREATOR VARCHAR2(255) NULL ,--creator

ID VARCHAR2(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1)  DEFAULT ('1') ,
CREATED VARCHAR2(32) NULL ,
CREATE_TIME DATE NULL ,
UPDATED VARCHAR2(32) NULL ,
UPDATE_TIME DATE NULL, 
ORG VARCHAR2(4000) NULL, 
 ORG_TREE VARCHAR2(4000) NULL 
)