CREATE TABLE tb_wait_done (
SSID NVARCHAR(200) NULL ,--ssid
DEVICE_SN NVARCHAR(200) NULL ,--deviceSn
DONE_STATUS NVARCHAR(200) NULL ,--doneStatus
CMD_CODE NVARCHAR(200) NULL ,--cmdCode
SUB_CMD NVARCHAR(200) NULL ,--subCmd
CMD_RETURN NVARCHAR(200) NULL ,--cmdReturn
SEND_TIME NVARCHAR(200) NULL ,--sendTime

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT ((1)) ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG NVARCHAR(4000) NULL, 
 ORG_TREE NVARCHAR(4000) NULL 
)