CREATE TABLE TB_WAIT_DONE (
SSID VARCHAR2(255) NULL ,--ssid
DEVICE_SN VARCHAR2(255) NULL ,--deviceSn
DONE_STATUS VARCHAR2(255) NULL ,--doneStatus
CMD_CODE VARCHAR2(255) NULL ,--cmdCode
SUB_CMD VARCHAR2(255) NULL ,--subCmd
CMD_RETURN VARCHAR2(255) NULL ,--cmdReturn
SEND_TIME VARCHAR2(255) NULL ,--sendTime

ID VARCHAR2(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1)  DEFAULT ('1') ,
CREATED VARCHAR2(32) NULL ,
CREATE_TIME DATE NULL ,
UPDATED VARCHAR2(32) NULL ,
UPDATE_TIME DATE NULL, 
ORG VARCHAR2(4000) NULL, 
 ORG_TREE VARCHAR2(4000) NULL 
)