CREATE TABLE tb_wait_done (
SSID VARCHAR(200) NULL ,-- ssid
DEVICE_SN VARCHAR(200) NULL ,-- deviceSn
DONE_STATUS VARCHAR(200) NULL ,-- doneStatus
CMD_CODE VARCHAR(200) NULL ,-- cmdCode
SUB_CMD VARCHAR(200) NULL ,-- subCmd
CMD_RETURN VARCHAR(200) NULL ,-- cmdReturn
SEND_TIME VARCHAR(200) NULL ,-- sendTime

ID VARCHAR(50) NOT NULL PRIMARY KEY ,
STATUS CHAR(1) NULL DEFAULT '1' ,
CREATED VARCHAR(32) NULL ,
CREATE_TIME DATETIME NULL ,
UPDATED VARCHAR(32) NULL ,
UPDATE_TIME DATETIME NULL, 
ORG text NULL, 
ORG_TREE text NULL
) ENGINE=InnoDB;
ALTER TABLE `tb_wait_done` ADD FULLTEXT `fidx_tb_wait_done_orgTree` (`ORG_TREE`);